name: Build
run-name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  - push
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.22621.0
          vsversion: 2022
      - name: Generate project
        run: .\msvc.bat
      - name: Build
        run: |
          cd msvc
          msbuild buxn-ls.sln /property:Configuration=RelWithDebInfo /property:Platform=x64
      - name: Create Windows archive
        run: |
          Compress-Archive -Path bin/RelWithDebInfo/buxn-ls.exe -DestinationPath buxn-ls-windows-amd64.zip
      - name: Upload Windows artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: buxn-ls-windows-amd64.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 2.37.1
      - name: Build
        run: BUILD_TYPE=RelWithDebInfo ./build
      - name: Create Linux archive
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          tar -czf buxn-ls-linux-amd64.tar.gz -C bin/RelWithDebInfo buxn-ls
      - name: Upload Linux artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: buxn-ls-linux-amd64.tar.gz
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1.2.1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake mold ninja llvm20
          run: |
            export PATH=/usr/local/llvm20/bin:$PATH
            BUILD_TYPE=RelWithDebInfo ./build
      - name: Create FreeBSD archive
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          tar -czf buxn-ls-freebsd-amd64.tar.gz -C bin/RelWithDebInfo buxn-ls
      - name: Upload FreeBSD artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: freebsd
          path: buxn-ls-freebsd-amd64.tar.gz
  release:
    name: Create Release
    needs: [build-linux, build-windows, build-freebsd]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Create GitHub prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
